name: R2L

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  R2V: 6.0.7

jobs:
  python-tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make pkg-config python3 python3-dev wget
    - name: Install radare2 release blobs
      run: |
        wget https://github.com/radareorg/radare2/releases/download/${{ env.R2V }}/radare2_${{ env.R2V }}_amd64.deb
        wget https://github.com/radareorg/radare2/releases/download/${{ env.R2V }}/radare2-dev_${{ env.R2V }}_amd64.deb
        sudo dpkg -i radare2_${{ env.R2V }}_amd64.deb
        sudo dpkg -i radare2-dev_${{ env.R2V }}_amd64.deb
    - name: Build Python
      run: ./configure && make -C python
    - name: Run Python plugin tests
      run: make tests
